version: '3'
services:
  shadowsocks:
    image: hopher/shadowsocks-libev:latest
    container_name: my_shadowsocks
    ports:
      - "8388:8388/tcp"
      - "8388:8388/udp"
    build:
      context: .
    environment:
      - METHOD=aes-256-gcm
      - PASSWORD=9MLSpPmNt
    restart: always